#!/usr/bin/env php
<?php
foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

use Tiimber\Cli\Application;
use Tiimber\Cli\Generate;

define('JSON_OPTIONS', JSON_PRETTY_PRINT + JSON_UNESCAPED_SLASHES);

$application = new Application();
$application->setBaseDir(__DIR__);
$application->add(new Generate\ProjectCommand());
$application->add(new Generate\ControllerCommand());
$application->add(new Generate\RouteCommand());
$application->run();